<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        foreach (self::SEED_DATA as $country){
            Country::updateOrCreate([
                'id' => $country['id']
            ], $country);
        }

    }

    const SEED_DATA = [
        [ "id" => 1, "name" => "Afghanistan", "phone_prefix" => "93", "code" => "AF"],
        [ "id" => 2, "name" => "Aland Islands", "phone_prefix" => "358", "code" => "AX"],
        [ "id" => 3, "name" => "Albania", "phone_prefix" => "355", "code" => "AL"],
        [ "id" => 4, "name" => "Algeria", "phone_prefix" => "213", "code" => "DZ"],
        [ "id" => 5, "name" => "AmericanSamoa", "phone_prefix" => "1-684", "code" => "AS"],
        [ "id" => 6, "name" => "Andorra", "phone_prefix" => "376", "code" => "AD"],
        [ "id" => 7, "name" => "Angola", "phone_prefix" => "244", "code" => "AO"],
        [ "id" => 8, "name" => "Anguilla", "phone_prefix" => "1-264", "code" => "AI"],
        [ "id" => 9, "name" => "Antarctica", "phone_prefix" => "672", "code" => "AQ"],
        [ "id" => 10, "name" => "Antigua and Barbuda", "phone_prefix" => "1268", "code" => "AG"],
        [ "id" => 11, "name" => "Argentina", "phone_prefix" => "54", "code" => "AR"],
        [ "id" => 12, "name" => "Armenia", "phone_prefix" => "374", "code" => "AM"],
        [ "id" => 13, "name" => "Aruba", "phone_prefix" => "297", "code" => "AW"],
        [ "id" => 14, "name" => "Australia", "phone_prefix" => "61", "code" => "AU"],
        [ "id" => 15, "name" => "Austria", "phone_prefix" => "43", "code" => "AT"],
        [ "id" => 16, "name" => "Azerbaijan", "phone_prefix" => "994", "code" => "AZ"],
        [ "id" => 17, "name" => "Bahamas", "phone_prefix" => "1-242", "code" => "BS"],
        [ "id" => 18, "name" => "Bahrain", "phone_prefix" => "973", "code" => "BH"],
        [ "id" => 19, "name" => "Bangladesh", "phone_prefix" => "880", "code" => "BD"],
        [ "id" => 20, "name" => "Barbados", "phone_prefix" => "1-246", "code" => "BB"],
        [ "id" => 21, "name" => "Belarus", "phone_prefix" => "375", "code" => "BY"],
        [ "id" => 22, "name" => "Belgium", "phone_prefix" => "32", "code" => "BE"],
        [ "id" => 23, "name" => "Belize", "phone_prefix" => "501", "code" => "BZ"],
        [ "id" => 24, "name" => "Benin", "phone_prefix" => "229", "code" => "BJ"],
        [ "id" => 25, "name" => "Bermuda", "phone_prefix" => "1-441", "code" => "BM"],
        [ "id" => 26, "name" => "Bhutan", "phone_prefix" => "975", "code" => "BT"],
        [ "id" => 27, "name" => "Bolivia, Plurinational State of", "phone_prefix" => "591", "code" => "BO"],
        [ "id" => 28, "name" => "Bosnia and Herzegovina", "phone_prefix" => "387", "code" => "BA"],
        [ "id" => 29, "name" => "Botswana", "phone_prefix" => "267", "code" => "BW"],
        [ "id" => 30, "name" => "Brazil", "phone_prefix" => "55", "code" => "BR"],
        [ "id" => 31, "name" => "British Indian Ocean Territory", "phone_prefix" => "246", "code" => "IO"],
        [ "id" => 32, "name" => "Brunei Darussalam", "phone_prefix" => "673", "code" => "BN"],
        [ "id" => 33, "name" => "Bulgaria", "phone_prefix" => "359", "code" => "BG"],
        [ "id" => 34, "name" => "Burkina Faso", "phone_prefix" => "226", "code" => "BF"],
        [ "id" => 35, "name" => "Burundi", "phone_prefix" => "257", "code" => "BI"],
        [ "id" => 36, "name" => "Cambodia", "phone_prefix" => "855", "code" => "KH"],
        [ "id" => 37, "name" => "Cameroon", "phone_prefix" => "237", "code" => "CM"],
        [ "id" => 38, "name" => "Canada", "phone_prefix" => "1", "code" => "CA"],
        [ "id" => 39, "name" => "Cape Verde", "phone_prefix" => "238", "code" => "CV"],
        [ "id" => 40, "name" => "Cayman Islands", "phone_prefix" => " 345", "code" => "KY"],
        [ "id" => 41, "name" => "Central African Republic", "phone_prefix" => "236", "code" => "CF"],
        [ "id" => 42, "name" => "Chad", "phone_prefix" => "235", "code" => "TD"],
        [ "id" => 43, "name" => "Chile", "phone_prefix" => "56", "code" => "CL"],
        [ "id" => 44, "name" => "China", "phone_prefix" => "86", "code" => "CN"],
        [ "id" => 45, "name" => "Christmas Island", "phone_prefix" => "61", "code" => "CX"],
        [ "id" => 46, "name" => "Cocos (Keeling) Islands", "phone_prefix" => "61", "code" => "CC"],
        [ "id" => 47, "name" => "Colombia", "phone_prefix" => "57", "code" => "CO"],
        [ "id" => 48, "name" => "Comoros", "phone_prefix" => "269", "code" => "KM"],
        [ "id" => 49, "name" => "Congo", "phone_prefix" => "242", "code" => "CG"],
        [ "id" => 50, "name" => "Congo, The Democratic Republic of the Congo", "phone_prefix" => "243", "code" => "CD"],
        [ "id" => 51, "name" => "Cook Islands", "phone_prefix" => "682", "code" => "CK"],
        [ "id" => 52, "name" => "Costa Rica", "phone_prefix" => "506", "code" => "CR"],
        [ "id" => 53, "name" => "Cote d'Ivoire", "phone_prefix" => "225", "code" => "CI"],
        [ "id" => 54, "name" => "Croatia", "phone_prefix" => "385", "code" => "HR"],
        [ "id" => 55, "name" => "Cuba", "phone_prefix" => "53", "code" => "CU"],
        [ "id" => 56, "name" => "Cyprus", "phone_prefix" => "357", "code" => "CY"],
        [ "id" => 57, "name" => "Czech Republic", "phone_prefix" => "420", "code" => "CZ"],
        [ "id" => 58, "name" => "Denmark", "phone_prefix" => "45", "code" => "DK"],
        [ "id" => 59, "name" => "Djibouti", "phone_prefix" => "253", "code" => "DJ"],
        [ "id" => 60, "name" => "Dominica", "phone_prefix" => "1-767", "code" => "DM"],
        [ "id" => 61, "name" => "Dominican Republic", "phone_prefix" => "1-849", "code" => "DO"],
        [ "id" => 62, "name" => "Ecuador", "phone_prefix" => "593", "code" => "EC"],
        [ "id" => 63, "name" => "Egypt", "phone_prefix" => "20", "code" => "EG"],
        [ "id" => 64, "name" => "El Salvador", "phone_prefix" => "503", "code" => "SV"],
        [ "id" => 65, "name" => "Equatorial Guinea", "phone_prefix" => "240", "code" => "GQ"],
        [ "id" => 66, "name" => "Eritrea", "phone_prefix" => "291", "code" => "ER"],
        [ "id" => 67, "name" => "Estonia", "phone_prefix" => "372", "code" => "EE"],
        [ "id" => 68, "name" => "Ethiopia", "phone_prefix" => "251", "code" => "ET"],
        [ "id" => 69, "name" => "Falkland Islands (Malvinas)", "phone_prefix" => "500", "code" => "FK"],
        [ "id" => 70, "name" => "Faroe Islands", "phone_prefix" => "298", "code" => "FO"],
        [ "id" => 71, "name" => "Fiji", "phone_prefix" => "679", "code" => "FJ"],
        [ "id" => 72, "name" => "Finland", "phone_prefix" => "358", "code" => "FI"],
        [ "id" => 73, "name" => "France", "phone_prefix" => "33", "code" => "FR"],
        [ "id" => 74, "name" => "French Guiana", "phone_prefix" => "594", "code" => "GF"],
        [ "id" => 75, "name" => "French Polynesia", "phone_prefix" => "689", "code" => "PF"],
        [ "id" => 76, "name" => "Gabon", "phone_prefix" => "241", "code" => "GA"],
        [ "id" => 77, "name" => "Gambia", "phone_prefix" => "220", "code" => "GM"],
        [ "id" => 78, "name" => "Georgia", "phone_prefix" => "995", "code" => "GE"],
        [ "id" => 79, "name" => "Germany", "phone_prefix" => "49", "code" => "DE"],
        [ "id" => 80, "name" => "Ghana", "phone_prefix" => "233", "code" => "GH"],
        [ "id" => 81, "name" => "Gibraltar", "phone_prefix" => "350", "code" => "GI"],
        [ "id" => 82, "name" => "Greece", "phone_prefix" => "30", "code" => "GR"],
        [ "id" => 83, "name" => "Greenland", "phone_prefix" => "299", "code" => "GL"],
        [ "id" => 84, "name" => "Grenada", "phone_prefix" => "1-473", "code" => "GD"],
        [ "id" => 85, "name" => "Guadeloupe", "phone_prefix" => "590", "code" => "GP"],
        [ "id" => 86, "name" => "Guam", "phone_prefix" => "1-671", "code" => "GU"],
        [ "id" => 87, "name" => "Guatemala", "phone_prefix" => "502", "code" => "GT"],
        [ "id" => 88, "name" => "Guernsey", "phone_prefix" => "44", "code" => "GG"],
        [ "id" => 89, "name" => "Guinea", "phone_prefix" => "224", "code" => "GN"],
        [ "id" => 90, "name" => "Guinea-Bissau", "phone_prefix" => "245", "code" => "GW"],
        [ "id" => 91, "name" => "Guyana", "phone_prefix" => "595", "code" => "GY"],
        [ "id" => 92, "name" => "Haiti", "phone_prefix" => "509", "code" => "HT"],
        [ "id" => 93, "name" => "Holy See (Vatican City State)", "phone_prefix" => "379", "code" => "VA"],
        [ "id" => 94, "name" => "Honduras", "phone_prefix" => "504", "code" => "HN"],
        [ "id" => 95, "name" => "Hong Kong", "phone_prefix" => "852", "code" => "HK"],
        [ "id" => 96, "name" => "Hungary", "phone_prefix" => "36", "code" => "HU"],
        [ "id" => 97, "name" => "Iceland", "phone_prefix" => "354", "code" => "IS"],
        [ "id" => 98, "name" => "India", "phone_prefix" => "91", "code" => "IN"],
        [ "id" => 99, "name" => "Indonesia", "phone_prefix" => "62", "code" => "ID"],
        [ "id" => 100, "name" => "Iran, Islamic Republic of Persian Gulf", "phone_prefix" => "98", "code" => "IR"],
        [ "id" => 101, "name" => "Iraq", "phone_prefix" => "964", "code" => "IQ"],
        [ "id" => 102, "name" => "Ireland", "phone_prefix" => "353", "code" => "IE"],
        [ "id" => 103, "name" => "Isle of Man", "phone_prefix" => "44", "code" => "IM"],
        [ "id" => 104, "name" => "Israel", "phone_prefix" => "972", "code" => "IL"],
        [ "id" => 105, "name" => "Italy", "phone_prefix" => "39", "code" => "IT"],
        [ "id" => 106, "name" => "Jamaica", "phone_prefix" => "1-876", "code" => "JM"],
        [ "id" => 107, "name" => "Japan", "phone_prefix" => "81", "code" => "JP"],
        [ "id" => 108, "name" => "Jersey", "phone_prefix" => "44", "code" => "JE"],
        [ "id" => 109, "name" => "Jordan", "phone_prefix" => "962", "code" => "JO"],
        [ "id" => 110, "name" => "Kazakhstan", "phone_prefix" => "7 7", "code" => "KZ"],
        [ "id" => 111, "name" => "Kenya", "phone_prefix" => "254", "code" => "KE"],
        [ "id" => 112, "name" => "Kiribati", "phone_prefix" => "686", "code" => "KI"],
        [ "id" => 113, "name" => "Korea, Democratic People's Republic of Korea", "phone_prefix" => "850", "code" => "KP"],
        [ "id" => 114, "name" => "Korea, Republic of South Korea", "phone_prefix" => "82", "code" => "KR"],
        [ "id" => 115, "name" => "Kuwait", "phone_prefix" => "965", "code" => "KW"],
        [ "id" => 116, "name" => "Kyrgyzstan", "phone_prefix" => "996", "code" => "KG"],
        [ "id" => 117, "name" => "Laos", "phone_prefix" => "856", "code" => "LA"],
        [ "id" => 118, "name" => "Latvia", "phone_prefix" => "371", "code" => "LV"],
        [ "id" => 119, "name" => "Lebanon", "phone_prefix" => "961", "code" => "LB"],
        [ "id" => 120, "name" => "Lesotho", "phone_prefix" => "266", "code" => "LS"],
        [ "id" => 121, "name" => "Liberia", "phone_prefix" => "231", "code" => "LR"],
        [ "id" => 122, "name" => "Libyan Arab Jamahiriya", "phone_prefix" => "218", "code" => "LY"],
        [ "id" => 123, "name" => "Liechtenstein", "phone_prefix" => "423", "code" => "LI"],
        [ "id" => 124, "name" => "Lithuania", "phone_prefix" => "370", "code" => "LT"],
        [ "id" => 125, "name" => "Luxembourg", "phone_prefix" => "352", "code" => "LU"],
        [ "id" => 126, "name" => "Macao", "phone_prefix" => "853", "code" => "MO"],
        [ "id" => 127, "name" => "Macedonia", "phone_prefix" => "389", "code" => "MK"],
        [ "id" => 128, "name" => "Madagascar", "phone_prefix" => "261", "code" => "MG"],
        [ "id" => 129, "name" => "Malawi", "phone_prefix" => "265", "code" => "MW"],
        [ "id" => 130, "name" => "Malaysia", "phone_prefix" => "60", "code" => "MY"],
        [ "id" => 131, "name" => "Maldives", "phone_prefix" => "960", "code" => "MV"],
        [ "id" => 132, "name" => "Mali", "phone_prefix" => "223", "code" => "ML"],
        [ "id" => 133, "name" => "Malta", "phone_prefix" => "356", "code" => "MT"],
        [ "id" => 134, "name" => "Marshall Islands", "phone_prefix" => "692", "code" => "MH"],
        [ "id" => 135, "name" => "Martinique", "phone_prefix" => "596", "code" => "MQ"],
        [ "id" => 136, "name" => "Mauritania", "phone_prefix" => "222", "code" => "MR"],
        [ "id" => 137, "name" => "Mauritius", "phone_prefix" => "230", "code" => "MU"],
        [ "id" => 138, "name" => "Mayotte", "phone_prefix" => "262", "code" => "YT"],
        [ "id" => 139, "name" => "Mexico", "phone_prefix" => "52", "code" => "MX"],
        [ "id" => 140, "name" => "Micronesia, Federated States of Micronesia", "phone_prefix" => "691", "code" => "FM"],
        [ "id" => 141, "name" => "Moldova", "phone_prefix" => "373", "code" => "MD"],
        [ "id" => 142, "name" => "Monaco", "phone_prefix" => "377", "code" => "MC"],
        [ "id" => 143, "name" => "Mongolia", "phone_prefix" => "976", "code" => "MN"],
        [ "id" => 144, "name" => "Montenegro", "phone_prefix" => "382", "code" => "ME"],
        [ "id" => 145, "name" => "Montserrat", "phone_prefix" => "1664", "code" => "MS"],
        [ "id" => 146, "name" => "Morocco", "phone_prefix" => "212", "code" => "MA"],
        [ "id" => 147, "name" => "Mozambique", "phone_prefix" => "258", "code" => "MZ"],
        [ "id" => 148, "name" => "Myanmar", "phone_prefix" => "95", "code" => "MM"],
        [ "id" => 149, "name" => "Namibia", "phone_prefix" => "264", "code" => "NA"],
        [ "id" => 150, "name" => "Nauru", "phone_prefix" => "674", "code" => "NR"],
        [ "id" => 151, "name" => "Nepal", "phone_prefix" => "977", "code" => "NP"],
        [ "id" => 152, "name" => "Netherlands", "phone_prefix" => "31", "code" => "NL"],
        [ "id" => 153, "name" => "Netherlands Antilles", "phone_prefix" => "599", "code" => "AN"],
        [ "id" => 154, "name" => "New Caledonia", "phone_prefix" => "687", "code" => "NC"],
        [ "id" => 155, "name" => "New Zealand", "phone_prefix" => "64", "code" => "NZ"],
        [ "id" => 156, "name" => "Nicaragua", "phone_prefix" => "505", "code" => "NI"],
        [ "id" => 157, "name" => "Niger", "phone_prefix" => "227", "code" => "NE"],
        [ "id" => 158, "name" => "Nigeria", "phone_prefix" => "234", "code" => "NG"],
        [ "id" => 159, "name" => "Niue", "phone_prefix" => "683", "code" => "NU"],
        [ "id" => 160, "name" => "Norfolk Island", "phone_prefix" => "672", "code" => "NF"],
        [ "id" => 161, "name" => "Northern Mariana Islands", "phone_prefix" => "1-670", "code" => "MP"],
        [ "id" => 162, "name" => "Norway", "phone_prefix" => "47", "code" => "NO"],
        [ "id" => 163, "name" => "Oman", "phone_prefix" => "968", "code" => "OM"],
        [ "id" => 164, "name" => "Pakistan", "phone_prefix" => "92", "code" => "PK"],
        [ "id" => 165, "name" => "Palau", "phone_prefix" => "680", "code" => "PW"],
        [ "id" => 166, "name" => "Palestinian Territory, Occupied", "phone_prefix" => "970", "code" => "PS"],
        [ "id" => 167, "name" => "Panama", "phone_prefix" => "507", "code" => "PA"],
        [ "id" => 168, "name" => "Papua New Guinea", "phone_prefix" => "675", "code" => "PG"],
        [ "id" => 169, "name" => "Paraguay", "phone_prefix" => "595", "code" => "PY"],
        [ "id" => 170, "name" => "Peru", "phone_prefix" => "51", "code" => "PE"],
        [ "id" => 171, "name" => "Philippines", "phone_prefix" => "63", "code" => "PH"],
        [ "id" => 172, "name" => "Pitcairn", "phone_prefix" => "872", "code" => "PN"],
        [ "id" => 173, "name" => "Poland", "phone_prefix" => "48", "code" => "PL"],
        [ "id" => 174, "name" => "Portugal", "phone_prefix" => "351", "code" => "PT"],
        [ "id" => 175, "name" => "Puerto Rico", "phone_prefix" => "1-939", "code" => "PR"],
        [ "id" => 176, "name" => "Qatar", "phone_prefix" => "974", "code" => "QA"],
        [ "id" => 177, "name" => "Romania", "phone_prefix" => "40", "code" => "RO"],
        [ "id" => 178, "name" => "Russia", "phone_prefix" => "7", "code" => "RU"],
        [ "id" => 179, "name" => "Rwanda", "phone_prefix" => "250", "code" => "RW"],
        [ "id" => 180, "name" => "Reunion", "phone_prefix" => "262", "code" => "RE"],
        [ "id" => 181, "name" => "Saint Barthelemy", "phone_prefix" => "590", "code" => "BL"],
        [ "id" => 182, "name" => "Saint Helena, Ascension and Tristan Da Cunha", "phone_prefix" => "290", "code" => "SH"],
        [ "id" => 183, "name" => "Saint Kitts and Nevis", "phone_prefix" => "1-869", "code" => "KN"],
        [ "id" => 184, "name" => "Saint Lucia", "phone_prefix" => "1-758", "code" => "LC"],
        [ "id" => 185, "name" => "Saint Martin", "phone_prefix" => "590", "code" => "MF"],
        [ "id" => 186, "name" => "Saint Pierre and Miquelon", "phone_prefix" => "508", "code" => "PM"],
        [ "id" => 187, "name" => "Saint Vincent and the Grenadines", "phone_prefix" => "1-784", "code" => "VC"],
        [ "id" => 188, "name" => "Samoa", "phone_prefix" => "685", "code" => "WS"],
        [ "id" => 189, "name" => "San Marino", "phone_prefix" => "378", "code" => "SM"],
        [ "id" => 190, "name" => "Sao Tome and Principe", "phone_prefix" => "239", "code" => "ST"],
        [ "id" => 191, "name" => "Saudi Arabia", "phone_prefix" => "966", "code" => "SA"],
        [ "id" => 192, "name" => "Senegal", "phone_prefix" => "221", "code" => "SN"],
        [ "id" => 193, "name" => "Serbia", "phone_prefix" => "381", "code" => "RS"],
        [ "id" => 194, "name" => "Seychelles", "phone_prefix" => "248", "code" => "SC"],
        [ "id" => 195, "name" => "Sierra Leone", "phone_prefix" => "232", "code" => "SL"],
        [ "id" => 196, "name" => "Singapore", "phone_prefix" => "65", "code" => "SG"],
        [ "id" => 197, "name" => "Slovakia", "phone_prefix" => "421", "code" => "SK"],
        [ "id" => 198, "name" => "Slovenia", "phone_prefix" => "386", "code" => "SI"],
        [ "id" => 199, "name" => "Solomon Islands", "phone_prefix" => "677", "code" => "SB"],
        [ "id" => 200, "name" => "Somalia", "phone_prefix" => "252", "code" => "SO"],
        [ "id" => 201, "name" => "South Africa", "phone_prefix" => "27", "code" => "ZA"],
        [ "id" => 202, "name" => "South Georgia and the South Sandwich Islands", "phone_prefix" => "500", "code" => "GS"],
        [ "id" => 203, "name" => "Spain", "phone_prefix" => "34", "code" => "ES"],
        [ "id" => 204, "name" => "Sri Lanka", "phone_prefix" => "94", "code" => "LK"],
        [ "id" => 205, "name" => "Sudan", "phone_prefix" => "249", "code" => "SD"],
        [ "id" => 206, "name" => "Suriname", "phone_prefix" => "597", "code" => "SR"],
        [ "id" => 207, "name" => "Svalbard and Jan Mayen", "phone_prefix" => "47", "code" => "SJ"],
        [ "id" => 208, "name" => "Swaziland", "phone_prefix" => "268", "code" => "SZ"],
        [ "id" => 209, "name" => "Sweden", "phone_prefix" => "46", "code" => "SE"],
        [ "id" => 210, "name" => "Switzerland", "phone_prefix" => "41", "code" => "CH"],
        [ "id" => 211, "name" => "Syrian Arab Republic", "phone_prefix" => "963", "code" => "SY"],
        [ "id" => 212, "name" => "Taiwan", "phone_prefix" => "886", "code" => "TW"],
        [ "id" => 213, "name" => "Tajikistan", "phone_prefix" => "992", "code" => "TJ"],
        [ "id" => 214, "name" => "Tanzania, United Republic of Tanzania", "phone_prefix" => "255", "code" => "TZ"],
        [ "id" => 215, "name" => "Thailand", "phone_prefix" => "66", "code" => "TH"],
        [ "id" => 216, "name" => "Timor-Leste", "phone_prefix" => "670", "code" => "TL"],
        [ "id" => 217, "name" => "Togo", "phone_prefix" => "228", "code" => "TG"],
        [ "id" => 218, "name" => "Tokelau", "phone_prefix" => "690", "code" => "TK"],
        [ "id" => 219, "name" => "Tonga", "phone_prefix" => "676", "code" => "TO"],
        [ "id" => 220, "name" => "Trinidad and Tobago", "phone_prefix" => "1-868", "code" => "TT"],
        [ "id" => 221, "name" => "Tunisia", "phone_prefix" => "216", "code" => "TN"],
        [ "id" => 222, "name" => "Turkey", "phone_prefix" => "90", "code" => "TR"],
        [ "id" => 223, "name" => "Turkmenistan", "phone_prefix" => "993", "code" => "TM"],
        [ "id" => 224, "name" => "Turks and Caicos Islands", "phone_prefix" => "1-649", "code" => "TC"],
        [ "id" => 225, "name" => "Tuvalu", "phone_prefix" => "688", "code" => "TV"],
        [ "id" => 226, "name" => "Uganda", "phone_prefix" => "256", "code" => "UG"],
        [ "id" => 227, "name" => "Ukraine", "phone_prefix" => "380", "code" => "UA"],
        [ "id" => 228, "name" => "United Arab Emirates", "phone_prefix" => "971", "code" => "AE"],
        [ "id" => 229, "name" => "United Kingdom", "phone_prefix" => "44", "code" => "GB"],
        [ "id" => 230, "name" => "United States", "phone_prefix" => "1", "code" => "US"],
        [ "id" => 231, "name" => "Uruguay", "phone_prefix" => "598", "code" => "UY"],
        [ "id" => 232, "name" => "Uzbekistan", "phone_prefix" => "998", "code" => "UZ"],
        [ "id" => 233, "name" => "Vanuatu", "phone_prefix" => "678", "code" => "VU"],
        [ "id" => 234, "name" => "Venezuela, Bolivarian Republic of Venezuela", "phone_prefix" => "58", "code" => "VE"],
        [ "id" => 235, "name" => "Vietnam", "phone_prefix" => "84", "code" => "VN"],
        [ "id" => 236, "name" => "Virgin Islands, British", "phone_prefix" => "1-284", "code" => "VG"],
        [ "id" => 237, "name" => "Virgin Islands, U.S.", "phone_prefix" => "1-340", "code" => "VI"],
        [ "id" => 238, "name" => "Wallis and Futuna", "phone_prefix" => "681", "code" => "WF"],
        [ "id" => 239, "name" => "Yemen", "phone_prefix" => "967", "code" => "YE"],
        [ "id" => 240, "name" => "Zambia", "phone_prefix" => "260", "code" => "ZM"],
        [ "id" => 241, "name" => "Zimbabwe", "phone_prefix" => "263", "code" => "ZW"]
    ];
}
